# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: db_meetapp
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: meetapp
    ports:
      - 5423:5432

volumes:
  db-data:
