# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: db_meetapp
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: meetapp
    ports:
      - 5423:5432
  
  mongo:
    image: mongo
    container_name: mongo_meetapp
    ports:
    - 27017:27017
    volumes:
      - /data/db:/data/db

  redis:
    image: redis
    container_name: redis_meetapp
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379

volumes:
  db-data:
  mongo-data:
